# Generated by Django 4.2.1 on 2023-06-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_bookmark_like_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='content_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='content_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='content_id',
            new_name='feed_id',
        ),
    ]
