# Generated by Django 4.2.1 on 2023-06-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_content_id_bookmark_feed_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
